//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH_ltcsdl_.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Hoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hoa()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
        }

        [Display(Name = "Mã Hoa")]
        public int MaHoa { get; set; }
        [Display(Name = "Tên hoa")]
        public string TenHoa { get; set; }
        [Display(Name = "Đơn giá")]
        public Nullable<double> DonGia { get; set; }
        [Display(Name = "Mã loại hoa")]
        public Nullable<int> MaLoaiHoa { get; set; }
        [Display(Name = "Hình ảnh")]
        public string HinhAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual TheLoai TheLoai { get; set; }
    }
}
